### ISSUE TITLE
Video Naming Bug

### ISSUE THREAD

**Issue by jaARke** [cameron-keene/ACE_Website#72]
We've identified an issue in the naming of the videos that are retrieved from YouTube. Specifically, when these videos are retrieved using the YouTube API, certain characters (&, $, etc.) in their titles are converted into a textual representation. Video titles that contain these characters are unclear and may serve to confuse users.

Also, our current method of retrieving videos includes a check for whether or not the database already contains a video with that title. This is problematic because renaming videos causes this check to fail, and multiple copies of the same video are added to the database under different names. This issue might be solved by hashing each video title upon retrieval from YouTube and comparing the hashes to the hashes stored in the database. This solution would require that hashes are not updated when a video is renamed.

### **Tasks:**
- [ ] Convert special characters in YouTube video titles before adding these titles to the database (regex?)
- [ ] Update video schema to include a hash variable
- [ ] Implement a hash method to be applied to all video titles retrieved from YouTube
- [ ] Implement a comparison of each hash to every existing hash in the database to prevent duplicate videos
