### ISSUE TITLE
Expand Login Functionality

### ISSUE THREAD

**Issue by jaARke** [cameron-keene/ACE_Website#74]
Currently, logging into the site is only possible with one set of admin credentials. We'd like to allow all club members to make accounts that can be used to login to the site with. In the future, these logins will have more value (tracking meeting attendance, matching interests to ongoing projects), but for now we'd like logged-in users to be able to join an ACE email list. This will allow them to be sent emails each time an announcement is made on the website.

### **Tasks:**
- [ ] Overhaul the current method of verifying user tokens to allow for multiple valid tokens associated with multiple logged-in users
- [ ] Update database's login schema to allow for expanded functionality
- [ ] Add page where users can create an account or login
- [ ] Add a button to the Announcements page for logged-in users to join the mailing list
- [ ] Implement automatic emailing each time an announcement is made using nodemailer
